### ISSUE TITLE
Fails with perls < 5.14

### ISSUE THREAD

**Issue by andk** [bluefeet/MooseX-BuildArgs#2]
As per subject. Sample fail report:

http://www.cpantesters.org/cpan/report/bc1a59b8-59fb-11e8-a862-afda493fcecb

Culprit seems to be the 'package' NAME BLOCK syntax.

If you want to keep the package block syntax it would be cool if you could predeclare the dependency. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

Thanks!

**Comment by bluefeet** [comment]
Thanks!
